apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
spec:
  ports:
  - port: 80
    node_port: 30443
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
